### ISSUE TITLE
[v4 Update] Update Block Exception After Update

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1326]
After updating from 3.5 to 4.0 alpha, the Update Block won't load and shows this error:

```
Error Loading Block: Rock Update Show Details
c:\inetpub\wwwroot\Blocks\Core\RockUpdate.ascx.cs(143): error CS0103: The name 'nbVersionIssue' does not exist in the current context

   at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at Rock.Web.UI.RockPage.OnInit(EventArgs e)

**Comment by azturner** [comment]
@bwitting , this actually only affects you since you are the only one that had previously updated to 3.5 prior to us modifying the 3.5 update to add some checks for SQL 2012. I'll send you the updated RockUpdate Block.

**Comment by bwitting** [comment]
@azturner figures! Thanks
